services:
  server:
    container_name: cmovie-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16-alpine  # smaller image
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
